### ISSUE TITLE
Type safety issues on imports.

### ISSUE THREAD

**Issue by IngoVals** [fakoua/cowsay#2]
Default deno install gives these errors on running Cowsay.

`No index signature with a parameter of type 'string' was found on type 'typeof import("https://deno.land/x/cowsay/src/balloon")'.
 return baloon[action](options.text, options.wrap ? options.wrapLength : null) + "\n" + cow(face);`

Need to be able to define the import as `{ [key: string]: any }` I guess.

Perhaps there is some config in deno that can turn this check on/off.

**Comment by fakoua** [comment]
Fixed with the latest PM, please use --reload to clear your cache.

thanks
